# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required
rust:
- nightly
- stable

env:
  global:
    - CRATE_NAME=raw-cpuid
    - RUSTFLAGS='-D warnings'

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd
    - env: TARGET=x86_64-unknown-freebsd
    - env: TARGET=x86_64-unknown-netbsd

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu


before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "PnWf/uxF327qqMDwqYoTXonXmJ6mvcNzTX6sYocXejepZ3D2HeLFJOa6SKXQuw6ql6nsJw92osfPaX6lv/AH51x2oNTc1DAZ1E64jRWG5SIT0r4qYYuYFYNXt8VeEcJepHvfMgMJLgXvGaFaWYAU+xr2Tj4TZMwg2fehnCaf4AE="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
