[package]
name = "raw-cpuid"
version = "3.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
build = "build.rs"

description = "A library to parse the x86 CPUID instruction, written in rust with no external dependencies. The implementation closely resembles the Intel CPUID manual description. The library does only depend on libcore."
homepage = "https://github.com/gz/rust-cpuid"
repository = "https://github.com/gz/rust-cpuid"
documentation = "https://docs.rs/raw-cpuid/"

readme = "README.md"
keywords = ["cpuid", "x86", "amd64", "os", "libcore"]
license = "MIT"

[[bin]]
name = "cpuid"
path = "src/bin/cpuid.rs"

[dependencies]
bitflags = "0.7"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[build-dependencies]
cc = "1"

[features]
nightly = []
serialize = ["serde", "serde_derive"]

