[package]
name = "raw-cpuid"
version = "0.2.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

description = "A library to parse the x86 cpuid instruction, written in rust with no external dependencies. In addition, this library can be used in no_std code and relies only on libcore."
repository = "https://github.com/gz/rust-cpuid"
documentation = "http://gz.github.io/rust-cpuid/raw_cpuid/"

readme = "README.md"
keywords = ["kernel", "os", "cpuid", "x86"]
license = "MIT"

[dependencies]
bitflags = "0.1.0"
