[package]
name = "raw-cpuid"
version = "0.0.4"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

description = "Library to read CPUID instruction data."
repository = "https://github.com/gz/rust-cpuid"

readme = "README.md"
keywords = ["kernel", "os", "cpuid", "x86"]
license = "MIT"

[dependencies]
bitflags = "0.1.0"
